{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "jumia.fullname" $ }}
  labels:
    {{- include "jumia.labels" $ | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ $.Values.externalSecret.secretStoreRef.name }}
    kind: {{ $.Values.externalSecret.secretStoreRef.kind }}
  refreshInterval: {{ $.Values.externalSecret.refreshInterval }}
  data:
  {{- range $k, $v := .Values.app.envFromExtSecret }}
    - secretKey: {{ $v.name }}
      remoteRef:
        key: {{ $v.key }}
  {{- end }}
{{- end }}