apiVersion: v1
kind: Service
metadata:
  name: {{ include "jumia.fullname" . }}
  labels:
    {{- include "jumia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jumia.selectorLabels" . | nindent 4 }}
